import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate,useParams,Routes,Route,Link} from 'react-router-dom';
import {BookOpen,LayoutDashboard,ClipboardList,BarChart3,FileText,Video,Newspaper,User,Search,Menu,X,Clock,CheckCircle2,ChevronLeft,ChevronRight} from 'lucide-react';
import './styles.css';
import {questionBank,tests} from './data/questionBank';

const navItems=[['Dashboard','/dashboard',LayoutDashboard],['Test Series','/tests',ClipboardList],['Notes','/notes',FileText],['Videos','/videos',Video],['Current Affairs','/current-affairs',Newspaper]];

function Layout({children}){const [open,setOpen]=useState(false);return <div className="app"><header><Link to="/dashboard" className="brand"><span>EF</span> ExamForge</Link><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'open':''}>{navItems.map(([n,p,I])=><Link onClick={()=>setOpen(false)} to={p} key={p}><I size={18}/>{n}</Link>)}</nav><Link className="profile" to="/dashboard"><User size={18}/> Student</Link></header><main>{children}</main><footer>© 2026 ExamForge · Built for focused preparation.</footer></div>}

function Dashboard(){return <Layout><div className="container"><section className="hero"><div><span className="eyebrow">SMART EXAM PRACTICE</span><h1>Prepare smarter.<br/><em>Perform better.</em></h1><p>Take realistic mocks, understand every mistake, and track your progress from one focused dashboard.</p><Link className="primary" to="/tests">Explore test series</Link></div><div className="heroCard"><div className="ring">78<span>%</span></div><div><b>Overall performance</b><p>↑ 8.4% this month</p></div></div></section><div className="stats">{[['Tests taken','18'],['Average score','78%'],['Accuracy','84%'],['Best rank','#142']].map(x=><div className="stat"><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><section className="sectionHead"><div><span className="eyebrow">CONTINUE LEARNING</span><h2>Recommended for you</h2></div><Link to="/tests">View all →</Link></section><div className="grid">{tests.slice(0,3).map(TestCard)}</div></div></Layout>}

function TestCard(t){return <article className="card" key={t.id}><div className="cardTop"><span className="pill">{t.exam}</span><span>{t.difficulty}</span></div><h3>{t.title}</h3><p>{t.questions} questions · {t.duration} min · {t.subjects.join(', ')}</p><Link className="darkBtn" to={'/test/'+t.id}>Start test</Link></article>}

function Tests(){return <Layout><div className="container"><span className="eyebrow">TEST SERIES</span><h1 className="pageTitle">Choose your next challenge</h1><div className="search"><Search size={19}/><input placeholder="Search tests, exams or subjects..."/></div><div className="filters">{['All','JEE Main','NEET','SSC CGL'].map(x=><button>{x}</button>)}</div><div className="grid">{tests.map(TestCard)}</div></div></Layout>}

function Resource({type}){let data=type==='Notes'?['Exam E-Notes','Structured revision notes, formulas and quick-reference material.']:type==='Videos'?['Video Courses','Focused lessons designed around important exam concepts.']:['Current Affairs','Daily exam-relevant updates and revision capsules.'];return <Layout><div className="container"><span className="eyebrow">LEARN</span><h1 className="pageTitle">{data[0]}</h1><p className="lead">{data[1]}</p><div className="grid">{['Physics','Chemistry','Mathematics'].map((x,i)=><article className="resource"><div className="resourceIcon">{['⚡','🧪','∑'][i]}</div><h3>{x}</h3><p>Curated resources for focused preparation.</p><button className="linkBtn">Explore →</button></article>)}</div></div></Layout>}

function TestRunner(){const {id}=useParams();const test=tests.find(x=>x.id===Number(id))||tests[0];const qs=questionBank.filter(q=>q.testId===test.id);const [i,setI]=useState(0),[ans,setAns]=useState({}),[seconds,setSeconds]=useState(test.duration*60),[done,setDone]=useState(false);useEffect(()=>{if(done)return;const t=setInterval(()=>setSeconds(s=>s>0?s-1:0),1000);return()=>clearInterval(t)},[done]);const score=useMemo(()=>qs.reduce((s,q,n)=>s+(ans[n]===q.answer?4:ans[n]===undefined?0:-1),0),[ans,qs]);if(done)return <Layout><div className="container result"><CheckCircle2 size={60}/><h1>Test submitted</h1><p>{test.title}</p><div className="resultStats"><b>{score}<small>Score</small></b><b>{Object.keys(ans).length}<small>Attempted</small></b><b>{Math.round(qs.filter((q,n)=>ans[n]===q.answer).length/Math.max(1,Object.keys(ans).length)*100)}%<small>Accuracy</small></b></div><Link className="primary" to="/tests">Back to tests</Link></div></Layout>;const q=qs[i%qs.length];return <Layout><div className="container runner"><div className="runnerHead"><div><b>{test.title}</b><small>{test.questions} questions · {test.duration} min</small></div><strong><Clock size={18}/>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong></div><div className="runnerGrid"><section className="question"><small>Question {i+1} of {qs.length}</small><h2>{q.question}</h2><div className="options">{q.options.map((o,n)=><button className={ans[i]===n?'selected':''} onClick={()=>setAns({...ans,[i]:n})}><b>{String.fromCharCode(65+n)}</b>{o}</button>)}</div><div className="runnerActions"><button onClick={()=>setI(Math.max(0,i-1))}><ChevronLeft/> Previous</button>{i===qs.length-1?<button className="submit" onClick={()=>setDone(true)}>Submit test</button>:<button className="primary" onClick={()=>setI(i+1)}>Next <ChevronRight/></button>}</div></section><aside className="palette"><b>Question palette</b><div>{qs.map((_,n)=><button className={n===i?'current':ans[n]!==undefined?'answered':''} onClick={()=>setI(n)}>{n+1}</button>)}</div><p><span className="dot answered"></span> Answered <span className="dot"></span> Unanswered</p></aside></div></div></Layout>}

function App(){return <Routes><Route path="/" element={<Dashboard/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/tests" element={<Tests/>}/><Route path="/test/:id" element={<TestRunner/>}/><Route path="/notes" element={<Resource type="Notes"/>}/><Route path="/videos" element={<Resource type="Videos"/>}/><Route path="/current-affairs" element={<Resource type="Current Affairs"/>}/></Routes>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);